import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";



const outFit = Outfit({
  variable: '--font-outfit',
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outFit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
          <main className="w-9/12 mx-auto">
            {children}
          </main>
          <Footer></Footer>
      </body>
    </html>
  );
}
